add firebase app distribution

diff --git a/.github/workflows/deploy_to_firebase_app_distripution.yaml b/.github/workflows/deploy_to_firebase_app_distripution.yaml
--- a/.github/workflows/deploy_to_firebase_app_distripution.yaml
+++ b/.github/workflows/deploy_to_firebase_app_distripution.yaml
@@ -5,6 +5,9 @@ on:
     branches:
       - main
 
+env:
+  ACTIONS_STEP_DEBUG: true
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -24,6 +27,16 @@ jobs:
       - name: Build APK
         run: flutter build apk --release
 
+      - name: Debug APK path
+        run: ls -l ./build/app/outputs/flutter-apk/
+
+      - name: Check if APK exists
+        run: |
+          if [ -f ./build/app/outputs/flutter-apk/app-release.apk ]; then
+            echo "APK file exists."
+          else
+            echo "APK file NOT found!" && exit 1
+          fi
 
       - name: Upload and Distribute App
         uses: mastersam07/firebase-app-distribution-action@v0.1
